# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('desconto', models.IntegerField()),
                ('lucro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Entrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('id_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('desconto', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('cancelado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('valor_venda', models.FloatField()),
                ('valor_custo', models.FloatField()),
                ('valor_desc', models.FloatField()),
                ('percent_desc', models.IntegerField()),
                ('promocao', models.FloatField()),
                ('qtd_estoque', models.IntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('total', models.FloatField()),
                ('desconto', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historico_venda',
            name='id_total',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Venda'),
        ),
        migrations.AddField(
            model_name='historico_venda',
            name='produto',
            field=models.ManyToManyField(to='loja.Produto'),
        ),
        migrations.AddField(
            model_name='historico_entrada',
            name='produto',
            field=models.ManyToManyField(to='loja.Produto'),
        ),
    ]
