# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='grupo',
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo',
            field=models.ManyToManyField(to='loja.Categoria'),
        ),
    ]
