# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor do item')),
                ('quantidade', models.DecimalField(decimal_places=0, default=1, max_digits=6, verbose_name='Quantidade')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entrada_det', to='loja.Entrada', verbose_name='Entrada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Preco')),
                ('quantidade', models.DecimalField(decimal_places=0, default=1, max_digits=6, verbose_name='Quantidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descricao')),
                ('qtd', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preco')),
                ('valor_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Valor de Custo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPrancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Tipo de Prancha',
                'verbose_name_plural': 'Tipos de Prancha',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='vendido em')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desconto R$')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Pagamento R$')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loja.Cliente', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loja.Produto')),
                ('tamanho', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2, verbose_name='Tamanho')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Cor', verbose_name='Cor')),
            ],
            options={
                'abstract': False,
            },
            bases=('loja.produto',),
        ),
        migrations.CreateModel(
            name='Prancha',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loja.Produto')),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Altura')),
                ('litragem', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Litragem')),
                ('tipo_prancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.TipoPrancha', verbose_name='Tipo de Prancha')),
            ],
            options={
                'verbose_name': 'Prancha',
                'verbose_name_plural': 'Pranchas',
            },
            bases=('loja.produto',),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda_det', to='loja.Venda', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='itementrada',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Produto', verbose_name='Produto'),
        ),
    ]
