# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='loja/static/imagem/'),
        ),
    ]
