CREATE TABLE PESSOA (
    nome varchar(250),
    id_pessoa SERIAL PRIMARY KEY,
    data_nascimento date,
    cpf varchar(11),
    email varchar(250),
    celular varchar(12),
    telefone varchar(11),
    emergencia varchar(12),
    genero varchar(10)
);

CREATE TABLE ALUNO (id_aluno SERIAL PRIMARY KEY)INHERITS (PESSOA);

CREATE TABLE PROFESSOR (id_professor SERIAL PRIMARY KEY)INHERITS (PESSOA);

CREATE TABLE VENDEDOR (id_vendedor SERIAL PRIMARY KEY)INHERITS (PESSOA);

CREATE TABLE SERVICO (
    id_servico SERIAL PRIMARY KEY,
    data DATE,
    valor FLOAT,
    desconto FLOAT,
    id_vendedor INT NOT NULL ,
    id_aluno INT NOT NULL
);

CREATE TABLE GUARDERIA (
    id_guarderia SERIAL PRIMARY KEY,
    vencimento DATE
)INHERITS (SERVICO);

CREATE TABLE ALUGUEL (
	id_aluguel SERIAL PRIMARY KEY
)INHERITS (SERVICO);

CREATE TABLE AULA (
	id_aula SERIAL PRIMARY KEY
)INHERITS (SERVICO);

CREATE TABLE DETALHE_GUARDERIA (
    id_detalhe_guarderia SERIAL PRIMARY KEY,
    valor FLOAT,
    id_guarderia INT NOT NULL,
    id_item INT NOT NULL
);

CREATE TABLE DETALHE_ALUGUEL (
    id_detalhe_aluguel SERIAL PRIMARY KEY,
    valor FLOAT,
    id_aluguel INT NOT NULL,
    id_prancha INT NOT NULL
);

CREATE TABLE DETALHE_AULA (
    id_detalhe_aula SERIAL PRIMARY KEY,
    valor FLOAT,
    id_aula INT NOT NULL,
    id_aula_marcada INT NOT NULL,
    id_professor INT NOT NULL
);

CREATE TABLE ITEM (
    id_item SERIAL PRIMARY KEY,
    nome VARCHAR(250),
    descricao VARCHAR(250)
);

CREATE TABLE PRANCHA (
    id_prancha SERIAL PRIMARY KEY,
    litragem FLOAT,
    altura FLOAT,
    id_tipo_prancha INT NOT NULL
);

CREATE TABLE AULA_MARCADA (
    id_aula_marcada SERIAL PRIMARY KEY,
    horario TIME,
    data DATE
);

CREATE TABLE TIPO_PRANCHA (
    id_tipo_prancha SERIAL PRIMARY KEY,
    descricao varchar(250)
);

ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_1 FOREIGN KEY (id_vendedor) REFERENCES VENDEDOR (id_vendedor);
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_2 FOREIGN KEY (id_aluno) REFERENCES ALUNO (id_aluno);  
ALTER TABLE DETALHE_GUARDERIA ADD CONSTRAINT FK_DETALHE_GUARDERIA_1 FOREIGN KEY (id_guarderia) REFERENCES GUARDERIA (id_guarderia);
ALTER TABLE DETALHE_GUARDERIA ADD CONSTRAINT FK_DETALHE_GUARDERIA_2 FOREIGN KEY (id_item) REFERENCES ITEM (id_item);
ALTER TABLE DETALHE_ALUGUEL ADD CONSTRAINT FK_DETALHE_ALUGUEL_0 FOREIGN KEY (id_aluguel) REFERENCES ALUGUEL (id_aluguel); 
ALTER TABLE DETALHE_ALUGUEL ADD CONSTRAINT FK_DETALHE_ALUGUEL_1 FOREIGN KEY (id_prancha) REFERENCES PRANCHA (id_prancha); 
ALTER TABLE DETALHE_AULA ADD CONSTRAINT FK_DETALHE_AULA_1 FOREIGN KEY (id_aula) REFERENCES AULA (id_aula);
ALTER TABLE DETALHE_AULA ADD CONSTRAINT FK_DETALHE_AULA_2 FOREIGN KEY (id_aula_marcada) REFERENCES AULA_MARCADA (id_aula_marcada);
ALTER TABLE DETALHE_AULA ADD CONSTRAINT FK_DETALHE_AULA_3 FOREIGN KEY (id_professor) REFERENCES PROFESSOR (id_professor);
ALTER TABLE PRANCHA ADD CONSTRAINT FK_PRANCHA_0 FOREIGN KEY (id_tipo_prancha) REFERENCES TIPO_PRANCHA (id_tipo_prancha);
