# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desconto R$')),
            ],
            options={
                'verbose_name_plural': 'Alugueis',
                'verbose_name': 'Aluguel',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='genero')),
                ('data_nascimento', models.DateField(verbose_name='Nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=18, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=18, verbose_name='Celular')),
                ('emergencia', models.CharField(max_length=18, verbose_name='Emergencia')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
                'verbose_name': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desconto R$')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Aluno', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name_plural': 'Aulas',
                'verbose_name': 'Aula',
            },
        ),
        migrations.CreateModel(
            name='AulaMarcada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('horario', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Aulas Marcadas',
                'verbose_name': 'Aula',
            },
        ),
        migrations.CreateModel(
            name='DetalheAluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor do item')),
                ('aluguel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluguel_det', to='servicos.Aluguel')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='Valor do item')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_det', to='servicos.Aula')),
                ('aula_marcada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_marcada_det', to='servicos.AulaMarcada')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheGuarderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor do item')),
            ],
        ),
        migrations.CreateModel(
            name='Guarderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('data', models.DateField(verbose_name='Data')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desconto R$')),
                ('vencimento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Aluno', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name_plural': 'Guarderia',
                'verbose_name': 'Guarderia',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Item')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name_plural': 'Itens da Guarderia',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Prancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
                ('altura', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Altura')),
                ('litragem', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Litragem')),
            ],
            options={
                'verbose_name_plural': 'Pranchas',
                'verbose_name': 'Prancha',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='genero')),
                ('data_nascimento', models.DateField(verbose_name='Nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(max_length=18, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=18, verbose_name='Celular')),
                ('emergencia', models.CharField(max_length=18, verbose_name='Emergencia')),
            ],
            options={
                'verbose_name_plural': 'Professores',
                'verbose_name': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='TipoPrancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Prancha',
                'verbose_name': 'Tipo de Prancha',
            },
        ),
        migrations.AddField(
            model_name='prancha',
            name='tipo_prancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.TipoPrancha', verbose_name='Tipo de Prancha'),
        ),
        migrations.AddField(
            model_name='detalheguarderia',
            name='guarderia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarderia_det', to='servicos.Guarderia'),
        ),
        migrations.AddField(
            model_name='detalheguarderia',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Item', verbose_name='itens'),
        ),
        migrations.AddField(
            model_name='detalheaula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_det', to='servicos.Professor'),
        ),
        migrations.AddField(
            model_name='detalhealuguel',
            name='prancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Prancha', verbose_name='pranchas'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.Aluno', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
