# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20170621_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='dinheiro',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='Dinheiro'),
        ),
    ]
