# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_aula_dinheiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='dinheiro',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='Pagamento R$'),
        ),
        migrations.AddField(
            model_name='aula',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='Pagamento R$'),
        ),
        migrations.AddField(
            model_name='guarderia',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='Pagamento R$'),
        ),
    ]
