# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20170621_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Pagamento R$'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Pagamento R$'),
        ),
        migrations.AlterField(
            model_name='guarderia',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Pagamento R$'),
        ),
    ]
