# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_auto_20170626_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('numero_de_alunos', models.IntegerField()),
            ],
        ),
    ]
